---
title: "Bellabeat Analysis Process"
output: html_document
date: "2023-04-01"
---

## Bellabeat Analysis Process Steps with R Programming

Install and load package tidyverse.

```{r cars}
install.packages("tidyverse")
library(tidyverse)
```


Import the data to data frames.

```{r pressure, echo=FALSE}
daily_activity <- read_csv("dailyActivity_merged.csv")
daily_calories <- read_csv("dailyCalories_merged.csv")
daily_intensities <- read_csv("dailyIntensities_merged.csv")
daily_sleepday <- read_csv("dailySleepDay_merged.csv")
daily_steps <- read_csv("dailySteps_merged.csv")
weight_info <- read_csv("weightLogInfo_merged.csv")
heart_rate <- read_csv("heartrate_seconds_merged.csv")
steps_hour <- read_csv("hourlySteps_merged.csv")

```

Take a deeper look to the data.

```{r}
colnames(daily_activity)
colnames(weight_info)
colnames(daily_calories)
colnames(daily_intensities)
colnames(daily_sleepday)
colnames(daily_steps)
colnames(heart_rate)
colnames(steps_hour)
str(daily_activity)
str(weight_info)
str(daily_calories)
str(daily_intensities)
str(daily_sleepday)
str(daily_steps)  
str(heart_rate)
str(steps_hour)
  
```

